### ISSUE TITLE
wheels

### ISSUE THREAD

**Issue by stonebig** [ericsnowcurrently/interpreters#1]
as it's not clear for casual programmer but enthousiast end-user to make a wheel from source, would it be possible that the project to provide wheels directly ? at least for Windows ?

the more easy it is to play with it right now, the more it will be a flury of initiatives around it for 3.12.0 final

**Comment by henryiii** [comment]
@ericsnowcurrently it looks like it would be pretty easy to build wheels with cibuildwheel now that we support 3.12 betas, would you like me to take a stab at it? (and if so, what CI do you like, or would you just like instructions for doing it locally?)

(We don't really recommend uploading them until the ABI is guaranteed stable, though, which is the last beta, unless you know what you are doing and are willing to reupload the fixed wheels with a new build number if the ABI does change - this seems like a potentially valid case to do that, so up to you about uploading them)

**Comment by ericsnowcurrently** [comment]
@henryiii  Yeah, give it a shot!

**Comment by henryiii** [comment]
I've tried it, and I get:

```pytb
src/_interpreters.c:6:10: fatal error: 'interpreteridobject.h' file not found
        #include "interpreteridobject.h"
                 ^~~~~~~~~~~~~~~~~~~~~~~
```

Is that expected? It's using 3.12 beta 4.

**Comment by henryiii** [comment]
This seems to have been a change in 3.11a2 (`interpreteridobject.h` -> `internal/interpreteridobject.h`):

https://github.com/python/cpython/blob/33838fedf7ed6ee907a49d042f8fa123178a1f9c/Misc/NEWS.d/3.11.0a2.rst#L1202

**Comment by ericsnowcurrently** [comment]
Yeah, looks like something's out of whack.  I'll take a look.

**Comment by stonebig** [comment]
No more urgent need: I can now build the wheel easily from interpreters_pep_734 source till you are stabilised in pep 734 ... also it may not help copilot to adapt to the new syntax, with no published  wheel
